# SQL Practice 11/28/2022

## Q1

A pharmacy wants to better understand how different drugs are selling. Given the data below, write a query to find the top most profitable drugs sold and how much profit they made. Write a query to find out which manufacturer is associated with the drugs that were not profitable and how much money the pharmacy lost on these drugs. Output the manufacturer, number of drugs, and total losses. Total losses should be in absolute value. Display the results with the highest losses on top.

Data Information

`pharmacy_sales` **Table**

Column Name | Type
------------|------
product_id | integer
units_sold | integer
total_sales | decimal
cogs | decimal
manufactuter | varchar
drug | varchar

`cogs` stands for "Cost of Goods Sold," which is the direct cost associated with producing the drug. `total_sales` is the revenue generated by all sales of the drug. You may assume there are no ties in profits and that no product has more than one manufacturer.

My solution is below

```SQL
WITH profit_table AS (
  SELECT manufacturer,
    drug,
    units_sold,
    (total_sales - cogs) AS profit
  FROM pharmacy_sales
)

SELECT manufacturer,
  COUNT(drug),
  SUM(ABS(profit)) as total_losses
 
  FROM profit_table
  
  WHERE profit < 0
  
  GROUP BY manufacturer

  ORDER BY total_losses DESC

  ;
```

So, first we generate a new table from the original table that contains the profit as a new column. Then, we group by the manufacturer, aggregating with count to find the number of drugs each manufacturer has, and taking the sum of the absolute value of the "profit" as the total losses. However, we only want to consider a drug that has a negative profit, i.e. a loss.

This could also be done without creating the new table first, and just filtering by the calculation directly and adjusting the value that we sum over. That solution is below.

```SQL
SELECT
    manufacturer,
    COUNT(drug),
    SUM(cogs - total_sales) AS total_losses

FROM pharmacy_sales

WHERE cogs > total_sales

GROUP BY manufacturer

ORDER BY total_losses DESC

;
```

This is more efficient, as it takes fewer lines of code, but it does not outline the thought process very well.